[0m17:08:02.122373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb93895dac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb93885c200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb93885e1b0>]}


============================== 17:08:02.125397 | 94eb9e3b-2f79-4420-aded-f48b6bdf0827 ==============================
[0m17:08:02.125397 [info ] [MainThread]: Running with dbt=1.9.8
[0m17:08:02.125954 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt ls --resource-type model', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:08:02.126368 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/batch_project/retail-sales-de/End-to-End-data-pipeline-Retail-store/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:08:02.127159 [debug] [MainThread]: Resource report: {"command_name": "list", "command_success": false, "command_wall_clock_time": 0.049704738, "process_in_blocks": "0", "process_kernel_time": 0.110015, "process_mem_max_rss": "94164", "process_out_blocks": "8", "process_user_time": 1.120159}
[0m17:08:02.127550 [debug] [MainThread]: Command `dbt ls` failed at 17:08:02.127455 after 0.05 seconds
[0m17:08:02.127871 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb938a5a6f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9382c9280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb93a9bd1f0>]}
[0m17:08:02.128187 [debug] [MainThread]: Flushing usage events
[0m17:08:02.477887 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:55:56.557267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e2a9c7a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e28629c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e2449700>]}


============================== 16:55:56.560864 | 4490d9a2-1ffe-4500-8f57-82ebb6261616 ==============================
[0m16:55:56.560864 [info ] [MainThread]: Running with dbt=1.9.8
[0m16:55:56.561455 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug --profile retail_pipeline --target dev_snowflake', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:55:56.572158 [info ] [MainThread]: dbt version: 1.9.8
[0m16:55:56.572613 [info ] [MainThread]: python version: 3.12.8
[0m16:55:56.572946 [info ] [MainThread]: python path: /root/batch_project/retail-sales-de/End-to-End-data-pipeline-Retail-store/.venv/bin/python
[0m16:55:56.573276 [info ] [MainThread]: os info: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[0m16:55:56.579391 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m16:55:56.580549 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m16:55:56.581176 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m16:55:56.581516 [info ] [MainThread]: Using dbt_project.yml file at /root/batch_project/retail-sales-de/End-to-End-data-pipeline-Retail-store/dbt_project.yml
[0m16:55:56.582245 [info ] [MainThread]: Configuration:
[0m16:55:56.582937 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m16:55:56.583462 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:55:56.583792 [info ] [MainThread]: Required dependencies:
[0m16:55:56.584188 [debug] [MainThread]: Executing "git --help"
[0m16:55:56.587031 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:55:56.587471 [debug] [MainThread]: STDERR: "b''"
[0m16:55:56.587776 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:55:56.588167 [info ] [MainThread]: Connection test skipped since no profile was found
[0m16:55:56.588618 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:55:56.589127 [info ] [MainThread]: Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "retail_pipeline", target "dev_snowflake" invalid: Runtime Error
    Could not find adapter type snowflake!


[0m16:55:56.589486 [info ] [MainThread]: Project loading failed for the following reason:
 project path </root/batch_project/retail-sales-de/End-to-End-data-pipeline-Retail-store/dbt_project.yml> not found

[0m16:55:56.590913 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.07928582, "process_in_blocks": "0", "process_kernel_time": 0.226454, "process_mem_max_rss": "95724", "process_out_blocks": "16", "process_user_time": 1.161811}
[0m16:55:56.591550 [debug] [MainThread]: Command `dbt debug` failed at 16:55:56.591416 after 0.08 seconds
[0m16:55:56.591942 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e22d1370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e2449700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1e2a9c7a0>]}
[0m16:55:56.592348 [debug] [MainThread]: Flushing usage events
[0m16:55:57.060419 [debug] [MainThread]: An error was encountered while trying to flush usage events
