2025-06-10 21:16:55,361 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 21:16:55,568 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 21:16:55,568 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 21:16:56,751 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:16:56,751 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=8df8ed77-f867-4be7-a36b-c0addf23cff7&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=3cc1b500-1536-49b3-b75c-5669101d1f6d
2025-06-10 21:16:57,057 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:16:58,645 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:16:58,646 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=bed3050f-ee06-479e-99a4-b51117d4bfee&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=25ed08e5-b27d-4d52-b416-bcea6c0be27d
2025-06-10 21:16:58,990 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:16:58,993 CRITICAL ETL process failed: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 21:20:26,907 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 21:20:27,056 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 21:20:27,056 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 21:20:28,046 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:20:28,047 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=80b6d7c0-4d12-478a-ae5d-881a70b2a0f3&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=e7e6e687-027b-41cd-9280-d8576a2c19fb
2025-06-10 21:20:28,821 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:20:30,221 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:20:30,225 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=a8583383-5b90-48ac-86ed-21e58dc13005&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=a61c586e-4700-4f00-882f-a85c31fb2c99
2025-06-10 21:20:30,526 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:20:30,528 CRITICAL ETL process failed: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 21:22:48,845 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 21:22:49,011 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 21:22:49,011 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 21:22:49,508 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:22:49,509 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=9aa5a97b-dbd0-44c7-8a0a-1c298301f664&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=c9d62309-2a4f-4e54-ade0-7d43ae19d803
2025-06-10 21:22:50,151 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:22:51,515 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:22:51,518 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=77e7f463-9e9c-4954-b90f-bcb681787865&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=43d362b0-05cd-4dd4-be72-1b8b769ed8d7
2025-06-10 21:22:52,135 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:22:52,142 CRITICAL ETL process failed: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 21:28:56,765 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 21:28:57,147 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 21:28:57,148 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 21:28:57,840 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:28:57,841 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=1ada4b5d-8f0c-4348-9148-ae74475f74a6&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=ead055e0-5a32-4120-9b4d-6c8dd6fbad4d
2025-06-10 21:28:58,233 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:28:59,121 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:28:59,122 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=cc3e6fd8-9b51-4095-ba37-5311b4c6bedb&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=da6b7713-afcf-4217-ab5e-c17ad0679b6d
2025-06-10 21:28:59,482 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 21:28:59,495 CRITICAL ETL process failed: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 22:46:39,854 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 22:46:40,087 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 22:46:40,088 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 22:46:40,934 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:46:40,935 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=6fc82b20-5656-4b67-8c10-20d725aae812&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=34e7ca23-7241-4d21-b86c-564833d6a4a4
2025-06-10 22:46:41,230 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:46:42,956 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:46:42,957 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=41356cc6-a0a4-4614-b2de-d464579a33b8&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=ff64bbab-2377-4926-ba5e-b26638543451
2025-06-10 22:46:43,512 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:46:43,523 CRITICAL ETL process failed: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 22:49:10,490 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 22:49:10,578 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 22:49:10,579 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 22:49:11,102 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:49:11,102 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=93a0fd7c-33d7-4f44-876f-f43ce360302c&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=8bcc4993-450e-47c2-94c0-eb0f04858078
2025-06-10 22:49:11,418 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:49:12,754 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:49:12,754 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=70e01475-856c-4361-afd5-b71e682a412e&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=8695f013-9745-47cc-9a9b-a0af2b7a812f
2025-06-10 22:49:13,279 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:49:13,281 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 22:58:28,597 WARNING python-dotenv could not parse statement starting at line 18
2025-06-10 22:58:28,597 WARNING python-dotenv could not parse statement starting at line 29
2025-06-10 22:58:28,597 WARNING python-dotenv could not parse statement starting at line 30
2025-06-10 22:58:28,597 WARNING python-dotenv could not parse statement starting at line 31
2025-06-10 22:58:28,635 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 22:58:28,726 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 22:58:28,727 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 22:58:29,290 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:58:29,291 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=89e2b695-eee1-4cef-8742-d77216e87813&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=0fdca82d-592d-4997-8810-356d1c08cc27
2025-06-10 22:58:29,833 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:58:31,392 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:58:31,392 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=c6f6d232-47f5-47ca-aa6f-faca514439f4&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=1888a7ed-463d-47ec-b4e7-1a5af3ffc84c
2025-06-10 22:58:31,712 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 22:58:31,721 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:01:02,090 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:01:02,233 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:01:02,233 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:01:02,752 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:01:02,753 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=5b96ea1d-687a-42fe-a9e4-4ec491da47cc&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=63ed4e3d-9782-4f3d-aa41-8b5d497e24c0
2025-06-10 23:01:03,484 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:01:05,241 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:01:05,242 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=884eb128-0e26-459e-b837-a02415c81825&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=daa6d536-afe1-41ff-b12b-925939b2039c
2025-06-10 23:01:05,554 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:01:05,560 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:04:08,963 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:04:09,176 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:04:09,176 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:04:09,719 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:04:09,720 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=446204e5-736e-4cda-af36-4c793a2042b3&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=c0c62c68-5382-446a-be2b-e97ff0cbf30b
2025-06-10 23:04:10,046 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:04:11,439 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:04:11,441 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=44e4c06a-a047-443c-95bc-d4e159d4735d&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=91751847-1342-47cc-a75a-26886d591c24
2025-06-10 23:04:11,752 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:04:11,760 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:08:14,282 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:08:14,387 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:08:14,388 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:08:14,836 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:08:14,837 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=8e5a77fa-b627-4bcd-9b1d-73409a5a4a11&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=8356fbc0-d108-4b44-a984-d9bf8cb25982
2025-06-10 23:08:15,124 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:08:16,433 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:08:16,434 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=64e3abf4-a120-4cab-8727-94fa0a1f1e17&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=c4cbc688-60de-4d90-9c3b-c68e391c3201
2025-06-10 23:08:16,771 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:08:16,775 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:10:00,089 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:10:00,275 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:10:00,276 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:10:00,893 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:10:00,894 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=d9e4c2db-0510-4b46-9d8d-aae8cee64ff9&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=ddaf5b36-91ea-48e7-8242-32a0c466e1ec
2025-06-10 23:10:01,243 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:10:02,749 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:10:02,751 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=09aa399f-e405-4811-a8c7-9bb1ff7877e3&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=1fbb3f3d-b4a5-43e9-9454-a315634684e3
2025-06-10 23:10:03,074 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:10:03,083 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:12:09,856 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:12:09,978 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:12:09,979 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:12:10,590 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:12:10,591 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=807f1f35-8389-4a3d-bb98-a98055432381&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=7690d2c3-1e91-4e92-942d-c08bbc27e5a1
2025-06-10 23:12:11,053 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:12:12,558 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:12:12,558 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=130d7254-2f3f-492d-8572-b70cc86ff5d2&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=b21fcfa3-10fc-4eca-9e9e-b7a80dc4fc60
2025-06-10 23:12:12,872 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:12:12,875 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:14:00,554 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:14:00,657 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:14:00,657 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:14:01,421 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:14:01,421 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=5644c2e3-0ee3-40fa-9d5b-e0a14d2d95fa&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=1c2b4eb4-fd0a-47a6-a4df-38b2fac75f20
2025-06-10 23:14:01,785 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:14:03,435 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:14:03,438 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=3cb1fd5a-21bd-4c0f-86c5-33a2d048f598&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=32410aa9-a29c-47af-bbde-52bdc3bf8abd
2025-06-10 23:14:03,772 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:14:03,777 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:15:31,845 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:15:32,098 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:15:32,099 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:15:33,089 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:15:33,090 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=96464ce1-1cec-4c90-8e91-d733f9e456f3&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=6f7bbbb1-e8f0-4e96-8722-f228fa5212ac
2025-06-10 23:15:33,409 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:15:34,715 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:15:34,715 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=886fcc13-4922-4e13-9b10-b381e1c0323a&databaseName=SF_CUST_ORDERS&schemaName=RAW_ORDERS&warehouse=COMPUTE_WH&roleName=ACCOUNT_ADMIN&request_guid=d96b95a5-68be-44c8-9ec1-7ae24241efa7
2025-06-10 23:15:34,983 WARNING Certificate did not match expected hostname: ldowbyr-yz98129.snowflakecomputing.com.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2025-06-10 23:15:34,988 ERROR Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
2025-06-10 23:23:56,382 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:23:56,484 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:23:56,484 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:23:57,920 INFO Ensured table RAW_ORDERS.orders exists.
2025-06-10 23:23:58,794 ERROR Error loading my_s3_stage/orders_20250611_011152.csv: 001011 (42601): 01bcf347-0001-1f8a-0001-db7e0001556a: SQL compilation error:
invalid URL prefix found in: 'my_s3_stage/orders_20250611_011152.csv'
2025-06-10 23:23:58,923 ERROR Error loading my_s3_stage/orders_20250611_040601.csv: 001011 (42601): 01bcf347-0001-200b-0001-db7e0001938a: SQL compilation error:
invalid URL prefix found in: 'my_s3_stage/orders_20250611_040601.csv'
2025-06-10 23:23:58,923 INFO ETL completed: no new files to load.
2025-06-10 23:27:35,589 INFO Found credentials in shared credentials file: ~/.aws/credentials
2025-06-10 23:27:35,696 INFO Snowflake Connector for Python Version: 3.15.0, Python Version: 3.12.8, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2025-06-10 23:27:35,696 INFO Connecting to GLOBAL Snowflake domain
2025-06-10 23:27:36,802 INFO Ensured table RAW_ORDERS.orders exists.
2025-06-10 23:27:40,782 INFO Loaded @my_s3_stage/orders_20250611_011152.csv into Snowflake.
2025-06-10 23:27:41,062 INFO Archived orders/orders_20250611_011152.csv → orders/processed/orders_20250611_011152.csv.
2025-06-10 23:27:43,734 INFO Loaded @my_s3_stage/orders_20250611_040601.csv into Snowflake.
2025-06-10 23:27:44,104 INFO Archived orders/orders_20250611_040601.csv → orders/processed/orders_20250611_040601.csv.
2025-06-10 23:27:44,105 INFO ETL completed successfully: data loaded & archived.
